// Oregon Tires Admin — Feature Categories & Data
// Extracted from admin/index.html inline script

var CLIENT_PRICE = 0;
var FREELANCER_RATE = 0.6;

var FEATURE_CATS = {
  A: { en: 'Booking, Scheduling & Availability', es: 'Reservas, Horarios y Disponibilidad' },
  B: { en: 'Employee Management & Job Assignment', es: 'Gesti\u00f3n de Empleados y Asignaci\u00f3n de Trabajo' },
  C: { en: 'Customer Data & CRM', es: 'Datos de Clientes y CRM' },
  D: { en: 'Notifications & Communication', es: 'Notificaciones y Comunicaci\u00f3n' },
  E: { en: 'Quotes, Pricing & Service Intake', es: 'Cotizaciones, Precios y Recepci\u00f3n de Servicio' },
  F: { en: 'Analytics & Reporting', es: 'An\u00e1lisis e Informes' },
  G: { en: 'Homepage, Branding & Content', es: 'P\u00e1gina Principal, Marca y Contenido' },
  H: { en: 'Translation & Bilingual', es: 'Traducci\u00f3n y Biling\u00fce' },
  I: { en: 'Completed / Needs Verification', es: 'Completado / Necesita Verificaci\u00f3n' },
  X: { en: 'Additional Features', es: 'Funciones Adicionales' }
};

var FEATURE_DATA = [
  // A. Booking, Scheduling & Availability
  { id:'A1', cat:'A', source:'client', status:'complete', price:1200, name_en:'Online Booking System', name_es:'Sistema de Reservas en L\u00ednea', desc_en:'Customers book appointments online with date/time, service type, and vehicle info.', desc_es:'Clientes reservan citas en l\u00ednea con fecha/hora, tipo de servicio e info del veh\u00edculo.' },
  { id:'A2', cat:'A', source:'client', status:'complete', price:600, name_en:'Date/Time Slot Selection', name_es:'Selecci\u00f3n de Fecha/Hora', desc_en:'Interactive calendar with 15-minute time slots and real-time availability.', desc_es:'Calendario interactivo con intervalos de 15 minutos y disponibilidad en tiempo real.' },
  { id:'A3', cat:'A', source:'client', status:'complete', price:300, name_en:'Service Type Selection', name_es:'Selecci\u00f3n de Tipo de Servicio', desc_en:'6 service categories selectable during booking.', desc_es:'6 categor\u00edas de servicio seleccionables durante la reserva.' },
  { id:'A4', cat:'A', source:'client', status:'complete', price:800, name_en:'Vehicle Info (VIN/Plate Lookup)', name_es:'Info del Veh\u00edculo (B\u00fasqueda VIN/Placa)', desc_en:'VIN decode and license plate lookup integrated into booking form.', desc_es:'Decodificaci\u00f3n VIN y b\u00fasqueda de placa integrados en el formulario de reserva.' },
  { id:'A5', cat:'A', source:'client', status:'complete', price:600, name_en:'Tire Size Lookup', name_es:'B\u00fasqueda de Tama\u00f1o de Llanta', desc_en:'"Find My Tire Size" tool with year/make/model fitment database.', desc_es:'Herramienta "Buscar Mi Tama\u00f1o de Llanta" con base de datos a\u00f1o/marca/modelo.' },
  { id:'A6', cat:'A', source:'client', status:'complete', price:250, name_en:'SMS Opt-in During Booking', name_es:'Opci\u00f3n SMS al Reservar', desc_en:'Customers can opt in to SMS notifications when booking.', desc_es:'Clientes pueden optar por notificaciones SMS al reservar.' },
  { id:'A7', cat:'A', source:'client', status:'complete', price:400, name_en:'Booking Confirmation Email', name_es:'Email de Confirmaci\u00f3n de Reserva', desc_en:'Bilingual confirmation email sent automatically after booking.', desc_es:'Email de confirmaci\u00f3n biling\u00fce enviado autom\u00e1ticamente despu\u00e9s de reservar.' },
  { id:'A8', cat:'A', source:'client', status:'complete', price:300, name_en:'Calendar Event (.ics)', name_es:'Evento de Calendario (.ics)', desc_en:'Downloadable .ics calendar event included with confirmation.', desc_es:'Evento de calendario .ics descargable incluido con la confirmaci\u00f3n.' },
  { id:'A9', cat:'A', source:'client', status:'complete', price:500, name_en:'Cancel/Reschedule via Token', name_es:'Cancelar/Reprogramar v\u00eda Token', desc_en:'Secure token-based links for cancellation and rescheduling.', desc_es:'Enlaces seguros basados en token para cancelaci\u00f3n y reprogramaci\u00f3n.' },
  { id:'A10', cat:'A', source:'client', status:'complete', price:400, name_en:'Configurable Business Hours', name_es:'Horario de Negocio Configurable', desc_en:'Admin UI for setting business hours per day of week.', desc_es:'Interfaz de admin para configurar horario por d\u00eda de la semana.' },
  { id:'A11', cat:'A', source:'client', status:'complete', price:350, name_en:'Holiday Calendar', name_es:'Calendario de D\u00edas Festivos', desc_en:'Admin-managed holidays automatically block booking slots.', desc_es:'D\u00edas festivos gestionados por admin bloquean autom\u00e1ticamente los horarios.' },
  { id:'A12', cat:'A', source:'client', status:'complete', price:500, name_en:'Multi-Bay Capacity per Slot', name_es:'Capacidad Multi-Bah\u00eda por Horario', desc_en:'Configurable concurrent appointment limit per time slot.', desc_es:'L\u00edmite configurable de citas concurrentes por horario.' },
  { id:'A13', cat:'A', source:'client', status:'complete', price:600, name_en:'Employee Schedule-Aware Availability', name_es:'Disponibilidad Basada en Horario de Empleados', desc_en:'Booking availability considers employee schedules and overrides.', desc_es:'Disponibilidad de reservas considera horarios y excepciones de empleados.' },
  { id:'A14', cat:'A', source:'client', status:'complete', price:200, name_en:'New vs Used Tire Preference', name_es:'Preferencia Llanta Nueva vs Usada', desc_en:'Customers select tire preference (new/used/either) during booking.', desc_es:'Clientes seleccionan preferencia de llanta (nueva/usada/cualquiera) al reservar.' },
  { id:'A15', cat:'A', source:'client', status:'complete', price:200, name_en:'Tire Count Field', name_es:'Campo de Cantidad de Llantas', desc_en:'Number of tires needed captured during booking.', desc_es:'N\u00famero de llantas necesarias capturado durante la reserva.' },

  // B. Employee Management & Job Assignment
  { id:'B1', cat:'B', source:'client', status:'complete', price:600, name_en:'Employee CRUD', name_es:'CRUD de Empleados', desc_en:'Full create, read, update, delete for employee records.', desc_es:'Crear, leer, actualizar y eliminar registros de empleados.' },
  { id:'B2', cat:'B', source:'client', status:'complete', price:500, name_en:'Weekly Schedules', name_es:'Horarios Semanales', desc_en:'Employee work schedules with day-of-week configuration.', desc_es:'Horarios de trabajo con configuraci\u00f3n por d\u00eda de la semana.' },
  { id:'B3', cat:'B', source:'client', status:'complete', price:400, name_en:'Schedule Date Overrides', name_es:'Excepciones de Horario por Fecha', desc_en:'Override regular schedule for specific dates.', desc_es:'Anular horario regular para fechas espec\u00edficas.' },
  { id:'B4', cat:'B', source:'client', status:'complete', price:350, name_en:'Skills & Certifications', name_es:'Habilidades y Certificaciones', desc_en:'Track employee skills and professional certifications.', desc_es:'Seguimiento de habilidades y certificaciones profesionales.' },
  { id:'B5', cat:'B', source:'client', status:'complete', price:400, name_en:'Assign Employee to Appointment', name_es:'Asignar Empleado a Cita', desc_en:'Admin assigns a technician to each appointment.', desc_es:'Admin asigna un t\u00e9cnico a cada cita.' },
  { id:'B6', cat:'B', source:'client', status:'complete', price:300, name_en:'Assignment Notification Email', name_es:'Email de Notificaci\u00f3n de Asignaci\u00f3n', desc_en:'Employee receives email when assigned to an appointment.', desc_es:'Empleado recibe email cuando se le asigna una cita.' },
  { id:'B7', cat:'B', source:'client', status:'complete', price:350, name_en:'Employee Schedule View', name_es:'Vista de Horario del Empleado', desc_en:'Employees can view their own schedule via member portal.', desc_es:'Empleados pueden ver su propio horario a trav\u00e9s del portal.' },
  { id:'B8', cat:'B', source:'client', status:'complete', price:350, name_en:'Assigned Work View', name_es:'Vista de Trabajo Asignado', desc_en:'Employees see their currently assigned repair orders.', desc_es:'Empleados ven sus \u00f3rdenes de reparaci\u00f3n asignadas.' },
  { id:'B9', cat:'B', source:'client', status:'complete', price:300, name_en:'Employee Customer List', name_es:'Lista de Clientes del Empleado', desc_en:'Employees view customers they have served.', desc_es:'Empleados ven los clientes que han atendido.' },
  { id:'B10', cat:'B', source:'client', status:'complete', price:350, name_en:'Per-Employee Daily Capacity', name_es:'Capacidad Diaria por Empleado', desc_en:'Configurable max daily appointments per employee.', desc_es:'M\u00e1ximo de citas diarias configurable por empleado.' },
  { id:'B11', cat:'B', source:'client', status:'not_started', price:500, name_en:'Auto-Assignment by Skills', name_es:'Auto-Asignaci\u00f3n por Habilidades', desc_en:'Automatically assign appointments based on employee skills and availability.', desc_es:'Asignar autom\u00e1ticamente citas basado en habilidades y disponibilidad.' },
  { id:'B12', cat:'B', source:'client', status:'complete', price:300, name_en:'Job Finished Notification', name_es:'Notificaci\u00f3n de Trabajo Terminado', desc_en:'Email and SMS sent to customer when job is complete.', desc_es:'Email y SMS enviados al cliente cuando el trabajo est\u00e1 completo.' },

  // C. Customer Data & CRM
  { id:'C1', cat:'C', source:'client', status:'complete', price:600, name_en:'Customer Records (Auto-Created)', name_es:'Registros de Clientes (Auto-Creados)', desc_en:'Customer records auto-created from bookings with email deduplication.', desc_es:'Registros de clientes creados autom\u00e1ticamente desde reservas con deduplicaci\u00f3n por email.' },
  { id:'C2', cat:'C', source:'client', status:'complete', price:500, name_en:'Vehicle Management', name_es:'Gesti\u00f3n de Veh\u00edculos', desc_en:'Full vehicle records with VIN, year/make/model, and tire sizes.', desc_es:'Registros completos de veh\u00edculos con VIN, a\u00f1o/marca/modelo y tama\u00f1os de llantas.' },
  { id:'C3', cat:'C', source:'client', status:'complete', price:400, name_en:'Appointment History', name_es:'Historial de Citas', desc_en:'Full appointment history linked to each customer.', desc_es:'Historial completo de citas vinculado a cada cliente.' },
  { id:'C4', cat:'C', source:'client', status:'complete', price:250, name_en:'Language Preference', name_es:'Preferencia de Idioma', desc_en:'Stored language preference for bilingual communications.', desc_es:'Preferencia de idioma guardada para comunicaciones biling\u00fces.' },
  { id:'C5', cat:'C', source:'client', status:'complete', price:500, name_en:'Customer Search', name_es:'B\u00fasqueda de Clientes', desc_en:'Search customers by name, email, or phone in admin panel.', desc_es:'Buscar clientes por nombre, email o tel\u00e9fono en el panel admin.' },
  { id:'C6', cat:'C', source:'client', status:'complete', price:500, name_en:'Visit Tracking (Check-in/out)', name_es:'Rastreo de Visitas (Entrada/Salida)', desc_en:'Shop floor check-in/check-out logging for each visit.', desc_es:'Registro de entrada/salida en el taller para cada visita.' },

  // D. Notifications & Communication
  { id:'D1', cat:'D', source:'client', status:'complete', price:400, name_en:'Booking Confirmation Email', name_es:'Email de Confirmaci\u00f3n de Reserva', desc_en:'Bilingual email sent upon booking completion.', desc_es:'Email biling\u00fce enviado al completar la reserva.' },
  { id:'D2', cat:'D', source:'client', status:'complete', price:500, name_en:'Day-Before Reminders', name_es:'Recordatorios del D\u00eda Anterior', desc_en:'Automated cron job sends reminders the evening before appointments.', desc_es:'Tarea cron automatizada env\u00eda recordatorios la noche anterior a las citas.' },
  { id:'D3', cat:'D', source:'client', status:'complete', price:300, name_en:'Employee Assignment Email', name_es:'Email de Asignaci\u00f3n a Empleado', desc_en:'Notification email to employee when assigned to a job.', desc_es:'Email de notificaci\u00f3n al empleado cuando se le asigna un trabajo.' },
  { id:'D4', cat:'D', source:'client', status:'complete', price:400, name_en:'Job Finished Email/SMS', name_es:'Email/SMS de Trabajo Terminado', desc_en:'Customer notified via email and SMS when vehicle is ready.', desc_es:'Cliente notificado por email y SMS cuando el veh\u00edculo est\u00e1 listo.' },
  { id:'D5', cat:'D', source:'client', status:'complete', price:500, name_en:'Inspection Report Email', name_es:'Email de Reporte de Inspecci\u00f3n', desc_en:'Digital vehicle inspection report sent to customer with token link.', desc_es:'Reporte de inspecci\u00f3n digital enviado al cliente con enlace seguro.' },
  { id:'D6', cat:'D', source:'client', status:'complete', price:600, name_en:'Estimate Email + Approval Link', name_es:'Email de Cotizaci\u00f3n + Enlace de Aprobaci\u00f3n', desc_en:'Estimate emailed with secure approval/decline link.', desc_es:'Cotizaci\u00f3n enviada por email con enlace seguro de aprobaci\u00f3n/rechazo.' },
  { id:'D7', cat:'D', source:'client', status:'complete', price:350, name_en:'Approval Confirmation Email', name_es:'Email de Confirmaci\u00f3n de Aprobaci\u00f3n', desc_en:'Confirmation email sent after estimate approval.', desc_es:'Email de confirmaci\u00f3n enviado despu\u00e9s de la aprobaci\u00f3n de cotizaci\u00f3n.' },
  { id:'D8', cat:'D', source:'client', status:'complete', price:350, name_en:'Vehicle Ready Email', name_es:'Email de Veh\u00edculo Listo', desc_en:'Notification when vehicle service is complete and ready for pickup.', desc_es:'Notificaci\u00f3n cuando el servicio est\u00e1 completo y listo para recoger.' },
  { id:'D9', cat:'D', source:'client', status:'complete', price:500, name_en:'Review Request Email', name_es:'Email de Solicitud de Rese\u00f1a', desc_en:'Automated post-service review request via daily cron.', desc_es:'Solicitud autom\u00e1tica de rese\u00f1a post-servicio mediante cron diario.' },
  { id:'D10', cat:'D', source:'client', status:'complete', price:400, name_en:'Estimate Expiry Reminder', name_es:'Recordatorio de Vencimiento de Cotizaci\u00f3n', desc_en:'Automated reminders for expiring estimates.', desc_es:'Recordatorios autom\u00e1ticos para cotizaciones por vencer.' },
  { id:'D11', cat:'D', source:'client', status:'planned', price:500, name_en:'SMS Notifications (Twilio)', name_es:'Notificaciones SMS (Twilio)', desc_en:'Full Twilio SMS integration. Scaffold exists, needs Twilio credentials.', desc_es:'Integraci\u00f3n completa de SMS con Twilio. Estructura existe, necesita credenciales.' },
  { id:'D12', cat:'D', source:'client', status:'complete', price:700, name_en:'Admin-Customer Messaging', name_es:'Mensajer\u00eda Admin-Cliente', desc_en:'Threaded messaging system between admin and customers.', desc_es:'Sistema de mensajer\u00eda con hilos entre admin y clientes.' },

  // E. Quotes, Pricing & Service Intake
  { id:'E1', cat:'E', source:'client', status:'complete', price:1200, name_en:'Estimate Builder', name_es:'Constructor de Cotizaciones', desc_en:'6 line item types: labor, parts, tire, fee, discount, sublet.', desc_es:'6 tipos de partidas: mano de obra, partes, llanta, cargo, descuento, subcontrato.' },
  { id:'E2', cat:'E', source:'client', status:'complete', price:600, name_en:'Auto-Generate from Inspection', name_es:'Auto-Generar desde Inspecci\u00f3n', desc_en:'One-click estimate creation from completed DVI.', desc_es:'Creaci\u00f3n de cotizaci\u00f3n con un clic desde inspecci\u00f3n completada.' },
  { id:'E3', cat:'E', source:'client', status:'complete', price:500, name_en:'Per-Item Approve/Decline', name_es:'Aprobar/Rechazar por Partida', desc_en:'Customers approve or decline individual estimate items.', desc_es:'Clientes aprueban o rechazan partidas individuales de la cotizaci\u00f3n.' },
  { id:'E4', cat:'E', source:'client', status:'complete', price:400, name_en:'8 Estimate Statuses', name_es:'8 Estados de Cotizaci\u00f3n', desc_en:'Full lifecycle: draft, sent, viewed, approved, partially_approved, declined, expired, revised.', desc_es:'Ciclo completo: borrador, enviado, visto, aprobado, parcialmente aprobado, rechazado, vencido, revisado.' },
  { id:'E5', cat:'E', source:'client', status:'complete', price:350, name_en:'Priority Cost Summary', name_es:'Resumen de Costos por Prioridad', desc_en:'Grouped by safety, recommended, and preventive categories.', desc_es:'Agrupado por categor\u00edas de seguridad, recomendado y preventivo.' },
  { id:'E6', cat:'E', source:'client', status:'complete', price:1500, name_en:'Care Plan Tiers (3 Levels)', name_es:'Planes de Cuidado (3 Niveles)', desc_en:'Subscription-based service plans with PayPal billing.', desc_es:'Planes de servicio por suscripci\u00f3n con facturaci\u00f3n PayPal.' },
  { id:'E7', cat:'E', source:'client', status:'complete', price:500, name_en:'Roadside Assistance Estimator', name_es:'Estimador de Asistencia en Carretera', desc_en:'Online estimator for roadside assistance pricing.', desc_es:'Estimador en l\u00ednea de precios de asistencia en carretera.' },
  { id:'E8', cat:'E', source:'client', status:'complete', price:300, name_en:'Service-Specific Intake Fields', name_es:'Campos de Recepci\u00f3n por Servicio', desc_en:'Tire preference and count fields for tire service bookings.', desc_es:'Campos de preferencia y cantidad de llantas para reservas de servicio.' },

  // F. Analytics & Reporting
  { id:'F1', cat:'F', source:'client', status:'complete', price:800, name_en:'Dashboard Overview Stats', name_es:'Estad\u00edsticas del Panel General', desc_en:'Key metrics: appointments, revenue, conversion rates.', desc_es:'M\u00e9tricas clave: citas, ingresos, tasas de conversi\u00f3n.' },
  { id:'F2', cat:'F', source:'client', status:'complete', price:600, name_en:'Employee Productivity', name_es:'Productividad de Empleados', desc_en:'Per-employee metrics and workload tracking.', desc_es:'M\u00e9tricas por empleado y seguimiento de carga de trabajo.' },
  { id:'F3', cat:'F', source:'client', status:'complete', price:600, name_en:'Revenue Trends', name_es:'Tendencias de Ingresos', desc_en:'Monthly estimate totals and revenue tracking.', desc_es:'Totales mensuales de cotizaciones y seguimiento de ingresos.' },
  { id:'F4', cat:'F', source:'client', status:'complete', price:500, name_en:'Conversion Funnel', name_es:'Embudo de Conversi\u00f3n', desc_en:'Track bookings through RO completion rates.', desc_es:'Seguimiento de reservas a trav\u00e9s de tasas de completaci\u00f3n de \u00f3rdenes.' },

  // G. Homepage, Branding & Content
  { id:'G1', cat:'G', source:'client', status:'complete', price:600, name_en:'Hero Section + Dynamic Background', name_es:'Secci\u00f3n Hero + Fondo Din\u00e1mico', desc_en:'API-loaded hero image with admin position controls.', desc_es:'Imagen hero cargada por API con controles de posici\u00f3n del admin.' },
  { id:'G2', cat:'G', source:'client', status:'complete', price:500, name_en:'7 Service Feature Cards', name_es:'7 Tarjetas de Servicio', desc_en:'Service cards linked to dedicated service pages.', desc_es:'Tarjetas de servicio vinculadas a p\u00e1ginas de servicio dedicadas.' },
  { id:'G3', cat:'G', source:'client', status:'complete', price:250, name_en:'About Section', name_es:'Secci\u00f3n Acerca De', desc_en:'Shop story and value proposition.', desc_es:'Historia del taller y propuesta de valor.' },
  { id:'G4', cat:'G', source:'client', status:'complete', price:400, name_en:'Reviews Section', name_es:'Secci\u00f3n de Rese\u00f1as', desc_en:'3 random Google Reviews displayed on homepage.', desc_es:'3 rese\u00f1as de Google aleatorias mostradas en la p\u00e1gina principal.' },
  { id:'G5', cat:'G', source:'client', status:'complete', price:500, name_en:'Photo Gallery', name_es:'Galer\u00eda de Fotos', desc_en:'Bilingual gallery with admin CRUD.', desc_es:'Galer\u00eda biling\u00fce con CRUD de admin.' },
  { id:'G6', cat:'G', source:'client', status:'complete', price:400, name_en:'Contact Form', name_es:'Formulario de Contacto', desc_en:'Bilingual contact form with admin inbox.', desc_es:'Formulario de contacto biling\u00fce con bandeja de admin.' },
  { id:'G7', cat:'G', source:'client', status:'complete', price:1200, name_en:'10 Service Detail Pages', name_es:'10 P\u00e1ginas de Detalle de Servicio', desc_en:'Bilingual with Schema.org markup for each service.', desc_es:'Biling\u00fces con marcado Schema.org para cada servicio.' },
  { id:'G8', cat:'G', source:'client', status:'complete', price:800, name_en:'8 Regional SEO Pages', name_es:'8 P\u00e1ginas SEO Regionales', desc_en:'Portland neighborhood pages for local search ranking.', desc_es:'P\u00e1ginas de vecindarios de Portland para posicionamiento local.' },
  { id:'G9', cat:'G', source:'client', status:'complete', price:600, name_en:'Blog', name_es:'Blog', desc_en:'Bilingual blog with admin editor.', desc_es:'Blog biling\u00fce con editor de admin.' },
  { id:'G10', cat:'G', source:'client', status:'complete', price:400, name_en:'FAQ Page', name_es:'P\u00e1gina de Preguntas Frecuentes', desc_en:'Accordion-style FAQ with bilingual content.', desc_es:'Preguntas frecuentes estilo acorde\u00f3n con contenido biling\u00fce.' },
  { id:'G11', cat:'G', source:'client', status:'complete', price:400, name_en:'Promotions', name_es:'Promociones', desc_en:'Time-limited promotional offers with placement targeting.', desc_es:'Ofertas promocionales con tiempo limitado y segmentaci\u00f3n de ubicaci\u00f3n.' },
  { id:'G12', cat:'G', source:'client', status:'complete', price:350, name_en:'Testimonials Management', name_es:'Gesti\u00f3n de Testimonios', desc_en:'Star-rated testimonials with admin CRUD.', desc_es:'Testimonios con calificaci\u00f3n por estrellas y CRUD de admin.' },
  { id:'G13', cat:'G', source:'client', status:'complete', price:350, name_en:'Newsletter / Subscribers', name_es:'Bolet\u00edn / Suscriptores', desc_en:'Email signup with subscriber management and export.', desc_es:'Registro de email con gesti\u00f3n de suscriptores y exportaci\u00f3n.' },
  { id:'G14', cat:'G', source:'client', status:'complete', price:300, name_en:'Service Images (8 Slots)', name_es:'Im\u00e1genes de Servicio (8 Espacios)', desc_en:'Admin-managed service card images with position/crop.', desc_es:'Im\u00e1genes de tarjetas de servicio con posici\u00f3n/recorte gestionadas por admin.' },
  { id:'G15', cat:'G', source:'client', status:'complete', price:300, name_en:'Dark Mode', name_es:'Modo Oscuro', desc_en:'System preference detection + manual toggle.', desc_es:'Detecci\u00f3n de preferencia del sistema + cambio manual.' },
  { id:'G16', cat:'G', source:'client', status:'complete', price:500, name_en:'PWA / Service Worker', name_es:'PWA / Service Worker', desc_en:'Progressive web app with offline fallback page.', desc_es:'Aplicaci\u00f3n web progresiva con p\u00e1gina de respaldo sin conexi\u00f3n.' },
  { id:'G17', cat:'G', source:'client', status:'complete', price:250, name_en:'Gallery Video Support', name_es:'Soporte de Video en Galer\u00eda', desc_en:'Video media type with YouTube/Vimeo embed support.', desc_es:'Tipo de medio video con soporte de incrustaci\u00f3n YouTube/Vimeo.' },
  { id:'G18', cat:'G', source:'client', status:'not_started', price:200, name_en:'Waiting Room Amenities Section', name_es:'Secci\u00f3n de Amenidades de Sala de Espera', desc_en:'Homepage section showcasing waiting room features.', desc_es:'Secci\u00f3n en p\u00e1gina principal mostrando caracter\u00edsticas de sala de espera.' },
  { id:'G19', cat:'G', source:'client', status:'complete', price:400, name_en:'Financing Page', name_es:'P\u00e1gina de Financiamiento', desc_en:'Dedicated financing options page with SEO config.', desc_es:'P\u00e1gina dedicada de opciones de financiamiento con configuraci\u00f3n SEO.' },
  { id:'G20', cat:'G', source:'client', status:'complete', price:200, name_en:'Social Media Links in Footer', name_es:'Enlaces de Redes Sociales en Pie de P\u00e1gina', desc_en:'Facebook and Instagram links in website footer.', desc_es:'Enlaces de Facebook e Instagram en el pie de p\u00e1gina del sitio.' },

  // H. Translation & Bilingual
  { id:'H1', cat:'H', source:'client', status:'complete', price:800, name_en:'EN/ES Toggle on All Pages', name_es:'Cambio EN/ES en Todas las P\u00e1ginas', desc_en:'Globe icon language switcher with data-t attribute system.', desc_es:'Cambio de idioma con icono de globo y sistema de atributos data-t.' },
  { id:'H2', cat:'H', source:'client', status:'complete', price:500, name_en:'Bilingual Auth Pages', name_es:'P\u00e1ginas de Autenticaci\u00f3n Biling\u00fces', desc_en:'Login, register, and password reset in both languages.', desc_es:'Inicio de sesi\u00f3n, registro y restablecimiento de contrase\u00f1a en ambos idiomas.' },
  { id:'H3', cat:'H', source:'client', status:'complete', price:500, name_en:'Bilingual Emails', name_es:'Emails Biling\u00fces', desc_en:'All notification emails sent in customer preferred language.', desc_es:'Todos los emails de notificaci\u00f3n enviados en el idioma preferido del cliente.' },

  // I. Completed / Needs Verification
  { id:'I1', cat:'I', source:'client', status:'complete', price:800, name_en:'Booking Flow End-to-End', name_es:'Flujo de Reserva Completo', desc_en:'4-step booking form through confirmation page.', desc_es:'Formulario de reserva de 4 pasos hasta p\u00e1gina de confirmaci\u00f3n.' },
  { id:'I2', cat:'I', source:'client', status:'complete', price:1000, name_en:'DVI System (35 Items)', name_es:'Sistema de Inspecci\u00f3n (35 \u00cdtems)', desc_en:'12 inspection categories, photo capture, traffic light rating.', desc_es:'12 categor\u00edas de inspecci\u00f3n, captura de fotos, calificaci\u00f3n semaf\u00f3rica.' },
  { id:'I3', cat:'I', source:'client', status:'complete', price:600, name_en:'Estimate Approval Flow', name_es:'Flujo de Aprobaci\u00f3n de Cotizaci\u00f3n', desc_en:'Token-based per-item approval with bilingual portal.', desc_es:'Aprobaci\u00f3n por partida basada en token con portal biling\u00fce.' },
  { id:'I4', cat:'I', source:'client', status:'complete', price:500, name_en:'RO Kanban Board', name_es:'Tablero Kanban de \u00d3rdenes', desc_en:'Drag-and-drop board with 11 status columns.', desc_es:'Tablero arrastrar y soltar con 11 columnas de estado.' },
  { id:'I5', cat:'I', source:'client', status:'complete', price:600, name_en:'Member Portal', name_es:'Portal de Miembros', desc_en:'Customer login with dashboard tabs.', desc_es:'Inicio de sesi\u00f3n de clientes con pesta\u00f1as de panel.' },
  { id:'I6', cat:'I', source:'client', status:'complete', price:400, name_en:'Google OAuth', name_es:'Google OAuth', desc_en:'Login and account linking via Google.', desc_es:'Inicio de sesi\u00f3n y vinculaci\u00f3n de cuenta v\u00eda Google.' },
  { id:'I7', cat:'I', source:'client', status:'complete', price:350, name_en:'Employee Schedule Management', name_es:'Gesti\u00f3n de Horarios de Empleados', desc_en:'Weekly schedules with date overrides.', desc_es:'Horarios semanales con excepciones por fecha.' },
  { id:'I8', cat:'I', source:'client', status:'complete', price:500, name_en:'Email Notification Chain', name_es:'Cadena de Notificaciones por Email', desc_en:'8+ automated email notification functions.', desc_es:'8+ funciones de notificaci\u00f3n autom\u00e1tica por email.' },
  { id:'I9', cat:'I', source:'client', status:'complete', price:800, name_en:'Care Plan Enrollment', name_es:'Inscripci\u00f3n en Plan de Cuidado', desc_en:'3-tier subscription system with PayPal.', desc_es:'Sistema de suscripci\u00f3n de 3 niveles con PayPal.' },
  { id:'I10', cat:'I', source:'client', status:'complete', price:1500, name_en:'Admin Panel (14 Tabs)', name_es:'Panel de Administraci\u00f3n (14 Pesta\u00f1as)', desc_en:'Full CRUD across all content types.', desc_es:'CRUD completo en todos los tipos de contenido.' },
  { id:'I11', cat:'I', source:'client', status:'complete', price:200, name_en:'Clean URLs', name_es:'URLs Limpias', desc_en:'.htaccess rewriting for friendly URLs.', desc_es:'Reescritura .htaccess para URLs amigables.' },
  { id:'I12', cat:'I', source:'client', status:'complete', price:250, name_en:'Image Optimization', name_es:'Optimizaci\u00f3n de Im\u00e1genes', desc_en:'AVIF/WebP content negotiation with automatic fallback.', desc_es:'Negociaci\u00f3n de contenido AVIF/WebP con respaldo autom\u00e1tico.' },

  // X. New Features — Developer-Added
  { id:'X1', cat:'X', source:'new', status:'complete', price:400, name_en:'VIN Decode (NHTSA API + Cache)', name_es:'Decodificaci\u00f3n VIN (API NHTSA + Cach\u00e9)', desc_en:'Decode any VIN using NHTSA vPIC API with permanent database cache.', desc_es:'Decodificar cualquier VIN usando API NHTSA vPIC con cach\u00e9 permanente en base de datos.' },
  { id:'X2', cat:'X', source:'new', status:'complete', price:350, name_en:'License Plate Lookup + Cache', name_es:'B\u00fasqueda de Placa + Cach\u00e9', desc_en:'License plate to vehicle lookup with database cache.', desc_es:'B\u00fasqueda de placa a veh\u00edculo con cach\u00e9 en base de datos.' },
  { id:'X3', cat:'X', source:'new', status:'complete', price:350, name_en:'Tire Fitment Lookup (90-Day Cache)', name_es:'B\u00fasqueda de Compatibilidad de Llantas (Cach\u00e9 90 D\u00edas)', desc_en:'Year/make/model tire fitment with 90-day database cache.', desc_es:'Compatibilidad de llantas a\u00f1o/marca/modelo con cach\u00e9 de 90 d\u00edas.' },
  { id:'X4', cat:'X', source:'new', status:'complete', price:250, name_en:'Configurable Business Hours Admin UI', name_es:'Interfaz Admin de Horario Configurable', desc_en:'Visual admin interface for managing business hours.', desc_es:'Interfaz visual de admin para gestionar horarios de negocio.' },
  { id:'X5', cat:'X', source:'new', status:'complete', price:200, name_en:'Holiday Calendar Admin', name_es:'Admin de Calendario de Festivos', desc_en:'Admin UI to manage holidays that block booking slots.', desc_es:'Interfaz admin para gestionar festivos que bloquean horarios.' },
  { id:'X6', cat:'X', source:'new', status:'complete', price:800, name_en:'RO Kanban Board (Drag-and-Drop)', name_es:'Tablero Kanban de \u00d3rdenes (Arrastrar y Soltar)', desc_en:'Visual kanban with drag-and-drop status transitions and time tracking.', desc_es:'Kanban visual con transiciones de estado arrastrar y soltar y seguimiento de tiempo.' },
  { id:'X7', cat:'X', source:'new', status:'complete', price:2000, name_en:'DVI System (35 Items, 12 Categories)', name_es:'Sistema de Inspecci\u00f3n (35 \u00cdtems, 12 Categor\u00edas)', desc_en:'Digital vehicle inspection with photo capture and traffic light system.', desc_es:'Inspecci\u00f3n digital de veh\u00edculos con captura de fotos y sistema semaf\u00f3rico.' },
  { id:'X8', cat:'X', source:'new', status:'complete', price:500, name_en:'Per-Item Estimate Approval Portal', name_es:'Portal de Aprobaci\u00f3n de Cotizaci\u00f3n por Partida', desc_en:'Customer-facing portal for granular estimate approval.', desc_es:'Portal para clientes para aprobaci\u00f3n granular de cotizaciones.' },
  { id:'X9', cat:'X', source:'new', status:'complete', price:300, name_en:'Print Support (Inspection + Estimate)', name_es:'Soporte de Impresi\u00f3n (Inspecci\u00f3n + Cotizaci\u00f3n)', desc_en:'Print-optimized layouts for inspection reports and estimates.', desc_es:'Dise\u00f1os optimizados para impresi\u00f3n de reportes de inspecci\u00f3n y cotizaciones.' },
  { id:'X10', cat:'X', source:'new', status:'complete', price:400, name_en:'Google Reviews Fetch + Cache', name_es:'Obtenci\u00f3n de Rese\u00f1as Google + Cach\u00e9', desc_en:'Automated Google Places API review fetching with database cache.', desc_es:'Obtenci\u00f3n autom\u00e1tica de rese\u00f1as de Google Places API con cach\u00e9.' },
  { id:'X11', cat:'X', source:'new', status:'complete', price:250, name_en:'Employee Skills/Certifications Tracking', name_es:'Seguimiento de Habilidades/Certificaciones', desc_en:'Track and manage employee skills and professional certifications.', desc_es:'Rastrear y gestionar habilidades y certificaciones profesionales.' },
  { id:'X12', cat:'X', source:'new', status:'complete', price:600, name_en:'Loyalty Points Ledger (Schema)', name_es:'Registro de Puntos de Lealtad (Esquema)', desc_en:'Customer loyalty_points table, rewards catalog, and points tracking functions.', desc_es:'Tabla loyalty_points de clientes, cat\u00e1logo de recompensas y funciones de seguimiento de puntos.' },
  { id:'X13', cat:'X', source:'new', status:'complete', price:700, name_en:'Messaging System (Admin \u2194 Customer)', name_es:'Sistema de Mensajer\u00eda (Admin \u2194 Cliente)', desc_en:'Threaded conversation system between admin and customers.', desc_es:'Sistema de conversaciones con hilos entre admin y clientes.' },
  { id:'X14', cat:'X', source:'new', status:'removed', price:500, name_en:'Google Calendar Sync (Removed)', name_es:'Sincronizaci\u00f3n Google Calendar (Eliminado)', desc_en:'Removed \u2014 Google Calendar integration disabled.', desc_es:'Eliminado \u2014 integraci\u00f3n con Google Calendar desactivada.' },
  { id:'X15', cat:'X', source:'new', status:'complete', price:300, name_en:'Error Tracking (3-Tier)', name_es:'Seguimiento de Errores (3 Niveles)', desc_en:'Sentry \u2192 Database \u2192 error_log graceful degradation.', desc_es:'Sentry \u2192 Base de Datos \u2192 error_log degradaci\u00f3n elegante.' },
  { id:'X16', cat:'X', source:'new', status:'complete', price:150, name_en:'API Versioning', name_es:'Versionamiento de API', desc_en:'/api/v1/ alias with X-API-Version header.', desc_es:'Alias /api/v1/ con encabezado X-API-Version.' },
  { id:'X17', cat:'X', source:'new', status:'complete', price:1000, name_en:'Enhanced Analytics Dashboard', name_es:'Panel de An\u00e1lisis Mejorado', desc_en:'Rich analytics with charts, trends, and conversion metrics.', desc_es:'An\u00e1lisis enriquecido con gr\u00e1ficos, tendencias y m\u00e9tricas de conversi\u00f3n.' },
  { id:'X18', cat:'X', source:'new', status:'complete', price:250, name_en:'Gallery Video Support', name_es:'Soporte de Video en Galer\u00eda', desc_en:'Video media type with YouTube/Vimeo embed support in gallery.', desc_es:'Tipo de medio video con soporte YouTube/Vimeo en la galer\u00eda.' },
  { id:'X19', cat:'X', source:'new', status:'complete', price:300, name_en:'Smart Account Linking', name_es:'Vinculaci\u00f3n Inteligente de Cuenta', desc_en:'Auto-link booking customers to member accounts by email.', desc_es:'Vincular autom\u00e1ticamente clientes de reservas a cuentas de miembros por email.' },
  { id:'X20', cat:'X', source:'new', status:'complete', price:200, name_en:'Feedback Page', name_es:'P\u00e1gina de Comentarios', desc_en:'Dedicated customer feedback collection page.', desc_es:'P\u00e1gina dedicada para recopilar comentarios de clientes.' },
  { id:'X21', cat:'X', source:'new', status:'complete', price:150, name_en:'System Status Page', name_es:'P\u00e1gina de Estado del Sistema', desc_en:'Health check dashboard for system monitoring.', desc_es:'Panel de verificaci\u00f3n de salud para monitoreo del sistema.' },
  { id:'X22', cat:'X', source:'new', status:'complete', price:350, name_en:'Site Settings Management', name_es:'Gesti\u00f3n de Configuraci\u00f3n del Sitio', desc_en:'Admin UI for editable site content and email templates.', desc_es:'Interfaz admin para contenido editable del sitio y plantillas de email.' },
  { id:'X23', cat:'X', source:'new', status:'complete', price:500, name_en:'Email Template Management (DB-Driven)', name_es:'Gesti\u00f3n de Plantillas de Email (Base de Datos)', desc_en:'Database-driven bilingual email templates with variable substitution.', desc_es:'Plantillas de email biling\u00fces basadas en base de datos con sustituci\u00f3n de variables.' },
  { id:'X24', cat:'X', source:'new', status:'complete', price:200, name_en:'Data Export', name_es:'Exportaci\u00f3n de Datos', desc_en:'Export appointments, customers, and other data to CSV.', desc_es:'Exportar citas, clientes y otros datos a CSV.' },
  { id:'X25', cat:'X', source:'new', status:'complete', price:200, name_en:'Cloudflare CDN Preparation', name_es:'Preparaci\u00f3n para CDN Cloudflare', desc_en:'Headers, content negotiation, and config ready for Cloudflare.', desc_es:'Encabezados, negociaci\u00f3n de contenido y configuraci\u00f3n listos para Cloudflare.' },
  { id:'X26', cat:'X', source:'new', status:'complete', price:300, name_en:'Image Content Negotiation (AVIF/WebP)', name_es:'Negociaci\u00f3n de Contenido de Im\u00e1genes (AVIF/WebP)', desc_en:'Automatic AVIF/WebP serving with PNG/JPG fallback.', desc_es:'Servicio autom\u00e1tico AVIF/WebP con respaldo PNG/JPG.' },
  { id:'X27', cat:'X', source:'new', status:'complete', price:350, name_en:'Visit Tracking (Check-in/out)', name_es:'Rastreo de Visitas (Entrada/Salida)', desc_en:'Shop floor visit logging with check-in and check-out times.', desc_es:'Registro de visitas en taller con tiempos de entrada y salida.' },
  { id:'X28', cat:'X', source:'new', status:'complete', price:250, name_en:'Estimate Expiry Reminders (Cron)', name_es:'Recordatorios de Vencimiento de Cotizaci\u00f3n (Cron)', desc_en:'Automated daily cron job for expiring estimate notifications.', desc_es:'Tarea cron diaria automatizada para notificaciones de cotizaciones por vencer.' },
  { id:'X29', cat:'X', source:'new', status:'complete', price:800, name_en:'Digital Invoices & Receipts', name_es:'Facturas y Recibos Digitales', desc_en:'Invoice generation from approved estimates with token-based customer view, print support, and email delivery.', desc_es:'Generaci\u00f3n de facturas desde cotizaciones aprobadas con vista de cliente basada en token, soporte de impresi\u00f3n y entrega por email.' },
  { id:'X30', cat:'X', source:'new', status:'complete', price:400, name_en:'Automated Service Reminders', name_es:'Recordatorios Autom\u00e1ticos de Servicio', desc_en:'Cron-based service reminders calculated from completed RO history with configurable intervals.', desc_es:'Recordatorios de servicio basados en cron calculados del historial de \u00f3rdenes completadas con intervalos configurables.' },
  { id:'X31', cat:'X', source:'new', status:'complete', price:800, name_en:'Customer Loyalty & Rewards', name_es:'Lealtad y Recompensas de Clientes', desc_en:'Points-based loyalty system with earn/redeem ledger, reward catalog, and member portal integration.', desc_es:'Sistema de lealtad basado en puntos con registro de acumulaci\u00f3n/canje, cat\u00e1logo de recompensas e integraci\u00f3n con portal de miembros.' },
  { id:'X32', cat:'X', source:'new', status:'complete', price:600, name_en:'Technician Job Tracking', name_es:'Rastreo de Trabajo de T\u00e9cnicos', desc_en:'Labor time clock-in/out per RO with billable hours tracking and productivity reports.', desc_es:'Control de tiempo de trabajo entrada/salida por orden con seguimiento de horas facturables e informes de productividad.' },
  { id:'X33', cat:'X', source:'new', status:'complete', price:1200, name_en:'Advanced Reporting Dashboard', name_es:'Panel de Informes Avanzado', desc_en:'Date range filters, revenue by service, customer acquisition trends, top customers, and labor efficiency metrics.', desc_es:'Filtros por rango de fechas, ingresos por servicio, tendencias de adquisici\u00f3n de clientes, mejores clientes y m\u00e9tricas de eficiencia laboral.' },
  { id:'X34', cat:'X', source:'new', status:'complete', price:500, name_en:'Customer Referral Program', name_es:'Programa de Referidos de Clientes', desc_en:'Referral codes with loyalty point rewards for referrer and referred customer.', desc_es:'C\u00f3digos de referido con recompensas de puntos de lealtad para referidor y cliente referido.' },
  { id:'X35', cat:'X', source:'new', status:'complete', price:700, name_en:'Waitlist & Walk-In Queue', name_es:'Lista de Espera y Cola de Walk-In', desc_en:'Walk-in queue management with estimated wait times, position tracking, and automated notifications.', desc_es:'Gesti\u00f3n de cola de walk-in con tiempos de espera estimados, seguimiento de posici\u00f3n y notificaciones autom\u00e1ticas.' },
  { id:'X36', cat:'X', source:'new', status:'complete', price:400, name_en:'Google Business Profile Sync', name_es:'Sincronizaci\u00f3n de Perfil de Google Business', desc_en:'Automated sync of business hours and holidays to Google Business Profile.', desc_es:'Sincronizaci\u00f3n autom\u00e1tica de horario de negocio y festivos al Perfil de Google Business.' },
  { id:'X37', cat:'X', source:'new', status:'complete', price:400, name_en:'Tire Quote Requests', name_es:'Solicitudes de Cotizaci\u00f3n de Llantas', desc_en:'Online tire quote request form with tire fitment lookup and admin management.', desc_es:'Formulario de solicitud de cotizaci\u00f3n de llantas en l\u00ednea con b\u00fasqueda de compatibilidad y gesti\u00f3n de admin.' }
];

// Category icons for overview display
var FEATURE_ICONS = {
  A: '\uD83D\uDCC5', B: '\uD83D\uDC77', C: '\uD83D\uDC65', D: '\uD83D\uDCE7',
  E: '\uD83D\uDCB0', F: '\uD83D\uDCCA', G: '\uD83C\uDFE0', H: '\uD83C\uDF10',
  I: '\u2705', X: '\uD83D\uDE80'
};

// Links to live pages for specific features
var FEATURE_LINKS = {
  A1: '/book-appointment/', G9: '/blog', G10: '/faq',
  E6: '/care-plan', E7: '/roadside-assistance',
  G7: '/tire-installation', G8: '/tires-se-portland',
  X20: '/feedback', X21: '/status', G6: '/contact',
  G5: '/gallery', G4: '/reviews', I5: '/members'
};

var COMING_SOON_DATA = [
  { id:'CS1', status:'scaffold_ready', emoji:'\uD83D\uDCF1', price:300,
    name_en:'SMS Notifications (Twilio)', name_es:'Notificaciones SMS (Twilio)',
    desc_en:'Automatic bilingual text message reminders before appointments. Reduces no-shows.',
    desc_es:'Recordatorios autom\u00e1ticos biling\u00fces por mensaje de texto antes de citas. Reduce ausencias.',
    note_en:'Scaffold ready \u2014 needs Twilio credentials', note_es:'Estructura lista \u2014 necesita credenciales Twilio' },
  { id:'CS2', status:'scaffold_ready', emoji:'\uD83D\uDCAC', price:400,
    name_en:'WhatsApp Integration', name_es:'Integraci\u00f3n WhatsApp',
    desc_en:'Send appointment confirmations and status updates via WhatsApp. Popular with Spanish-speaking customers.',
    desc_es:'Env\u00edo de confirmaciones y actualizaciones de estado por WhatsApp. Popular entre clientes hispanohablantes.',
    note_en:'Scaffold ready \u2014 needs Twilio WhatsApp credentials', note_es:'Estructura lista \u2014 necesita credenciales WhatsApp de Twilio' },
  { id:'CS3', status:'planned', emoji:'\uD83D\uDCB3', price:500,
    name_en:'Stripe Payment Integration', name_es:'Integraci\u00f3n de Pagos Stripe',
    desc_en:'Accept credit/debit cards directly on the website alongside PayPal. Apple Pay and Google Pay support.',
    desc_es:'Aceptar tarjetas de cr\u00e9dito/d\u00e9bito directamente en el sitio junto con PayPal. Soporte Apple Pay y Google Pay.' },
  { id:'CS4', status:'planned', emoji:'\uD83D\uDCE6', price:1500,
    name_en:'Inventory Management', name_es:'Gesti\u00f3n de Inventario',
    desc_en:'Track tire stock, parts, and supplies. Low-stock alerts. Link inventory to repair orders.',
    desc_es:'Rastrear stock de llantas, partes y suministros. Alertas de bajo stock. Vincular a \u00f3rdenes de reparaci\u00f3n.' },
  { id:'CS5', status:'planned', emoji:'\uD83D\uDED2', price:2000,
    name_en:'Online Tire Ordering', name_es:'Pedidos de Llantas en L\u00ednea',
    desc_en:'Customer-facing tire catalog with fitment lookup, pricing, and online ordering with installation scheduling.',
    desc_es:'Cat\u00e1logo de llantas con b\u00fasqueda de compatibilidad, precios y pedidos en l\u00ednea con programaci\u00f3n de instalaci\u00f3n.' },
  { id:'CS6', status:'planned', emoji:'\uD83D\uDE9A', price:2000,
    name_en:'Fleet Management Portal', name_es:'Portal de Gesti\u00f3n de Flotillas',
    desc_en:'Dedicated dashboard for fleet customers: manage multiple vehicles, schedule bulk services, track spending.',
    desc_es:'Panel dedicado para clientes de flotilla: gestionar m\u00faltiples veh\u00edculos, servicios masivos, rastrear gastos.' },
  { id:'CS7', status:'planned', emoji:'\uD83D\uDCE7', price:800,
    name_en:'Automated Follow-Up Campaigns', name_es:'Campa\u00f1as de Seguimiento Automatizadas',
    desc_en:'Marketing email sequences based on service history: tire rotation, oil change, brake inspection reminders.',
    desc_es:'Secuencias de email marketing basadas en historial: rotaci\u00f3n de llantas, cambio de aceite, inspecciones de frenos.' },
  { id:'CS8', status:'planned', emoji:'\uD83D\uDD27', price:600,
    name_en:'Tire Recommendation Engine', name_es:'Motor de Recomendaci\u00f3n de Llantas',
    desc_en:'When a customer vehicle is on file, proactively show compatible tire options with pricing during booking or on dashboard.',
    desc_es:'Cuando un veh\u00edculo est\u00e1 en archivo, mostrar opciones de llantas compatibles con precios durante la reserva o en el panel.' },
  { id:'CS9', status:'planned', emoji:'\uD83C\uDF1F', price:400,
    name_en:'Seasonal Promotion Automation', name_es:'Automatizaci\u00f3n de Promociones Estacionales',
    desc_en:'Automatically activate/deactivate promotions by date range. Schedule winter tire deals, summer A/C checks in advance.',
    desc_es:'Activar/desactivar promociones autom\u00e1ticamente por rango de fechas. Programar ofertas de invierno y verano.' },
  { id:'CS10', status:'planned', emoji:'\uD83E\uDD16', price:400,
    name_en:'Auto-Assignment by Skills', name_es:'Auto-Asignaci\u00f3n por Habilidades',
    desc_en:'Automatically assign appointments to technicians based on their skills and current availability.',
    desc_es:'Asignar autom\u00e1ticamente citas a t\u00e9cnicos basado en sus habilidades y disponibilidad actual.' },
  { id:'CS11', status:'planned', emoji:'\uD83D\uDECB', price:150,
    name_en:'Waiting Room Amenities Section', name_es:'Secci\u00f3n de Amenidades de Sala de Espera',
    desc_en:'Homepage section showcasing waiting room features: WiFi, coffee, TV, comfortable seating.',
    desc_es:'Secci\u00f3n en p\u00e1gina principal mostrando caracter\u00edsticas de sala de espera: WiFi, caf\u00e9, TV, asientos c\u00f3modos.' },
  { id:'CS12', status:'future', emoji:'\uD83D\uDCCD', price:3000,
    name_en:'Multi-Location Support', name_es:'Soporte Multi-Ubicaci\u00f3n',
    desc_en:'Support for multiple shop locations with location-specific scheduling, inventory, and reporting.',
    desc_es:'Soporte para m\u00faltiples ubicaciones con horarios, inventario e informes por sucursal.' }
];
