-- Register new 1vsM satellite sites (mirror of hiphop.world engine_sites)
-- All site_keys follow naming convention: dots replaced with underscores
-- Idempotent: uses INSERT IGNORE

INSERT IGNORE INTO engine_sites (site_key, name, domain, site_type, directory_name, visual_network, footer_badge, status) VALUES
('ape_city', 'Ape City', 'ape.city', '1vsm', '---ape.city', 'independent', '1vsm', 'development'),
('award_city', 'Award City', 'award.city', '1vsm', '---award.city', 'independent', '1vsm', 'development'),
('awards_city', 'Awards City', 'awards.city', '1vsm', '---awards.city', 'independent', '1vsm', 'development'),
('bars_gives', 'Bars Gives', 'bars.gives', '1vsm', '---bars.gives', 'independent', '1vsm', 'development'),
('bitcoinhiphop_com', 'Bitcoin Hip Hop', 'bitcoinhiphop.com', '1vsm', '---bitcoinhiphop.com', 'independent', '1vsm', 'development'),
('cambatta_com', 'Cambatta', 'cambatta.com', '1vsm', '---cambatta.com', 'independent', '1vsm', 'development'),
('cleveland_my', 'Cleveland My', 'cleveland.my', '1vsm', '---cleveland.my', 'independent', '1vsm', 'development'),
('dcrap_com', 'DC Rap', 'dcrap.com', '1vsm', '---dcrap.com', 'independent', '1vsm', 'development'),
('dmv_events', 'DMV Events', 'dmv.events', '1vsm', '---dmv.events', 'independent', '1vsm', 'development'),
('dmv_foundation', 'DMV Foundation', 'dmv.foundation', '1vsm', '---dmv.foundation', 'independent', '1vsm', 'development'),
('dmv_gives', 'DMV Gives', 'dmv.gives', '1vsm', '---dmv.gives', 'independent', '1vsm', 'development'),
('dmv_live', 'DMV Live', 'dmv.live', '1vsm', '---dmv.live', 'independent', '1vsm', 'development'),
('dmv_pics', 'DMV Pics', 'dmv.pics', '1vsm', '---dmv.pics', 'independent', '1vsm', 'development'),
('dmv_show', 'DMV Show', 'dmv.show', '1vsm', '---dmv.show', 'independent', '1vsm', 'development'),
('dmv_studio', 'DMV Studio', 'dmv.studio', '1vsm', '---dmv.studio', 'independent', '1vsm', 'development'),
('dmvrap_com', 'DMV Rap', 'dmvrap.com', '1vsm', '---dmvrap.com', 'independent', '1vsm', 'development'),
('flexmathews_com', 'Flex Mathews', 'flexmathews.com', '1vsm', '---flexmathews.com', 'independent', '1vsm', 'development'),
('hhdb_com', 'HH DB', 'hhdb.com', '1vsm', '---hhdb.com', 'independent', '1vsm', 'development'),
('iwitty_hair', 'iWitty Hair', 'iwitty.hair', '1vsm', '---iwitty.hair', 'independent', '1vsm', 'development'),
('jusallah_com', 'Jus Allah', 'jusallah.com', '1vsm', '---jusallah.com', 'independent', '1vsm', 'development'),
('nfta_pe', 'NFTA.pe', 'nfta.pe', '1vsm', '---nfta.pe', 'independent', '1vsm', 'development'),
('onevsmany_com', 'One vs Many', 'onevsmany.com', '1vsm', '---onevsmany.com', 'independent', '1vsm', 'development'),
('pdx_directory', 'PDX Directory', 'pdx.directory', '1vsm', '---pdx.directory', 'independent', '1vsm', 'development'),
('pdx_dog', 'PDX Dog', 'pdx.dog', '1vsm', '---pdx.dog', 'independent', '1vsm', 'development'),
('pdx_foundation', 'PDX Foundation', 'pdx.foundation', '1vsm', '---pdx.foundation', 'independent', '1vsm', 'development'),
('pdx_marketing', 'PDX Marketing', 'pdx.marketing', '1vsm', '---pdx.marketing', 'independent', '1vsm', 'development'),
('portland_dog', 'Portland Dog', 'portland.dog', '1vsm', '---portland.dog', 'independent', '1vsm', 'development'),
('portland_food', 'Portland Food', 'portland.food', '1vsm', '---portland.food', 'independent', '1vsm', 'development'),
('portland_marketing', 'Portland Marketing', 'portland.marketing', '1vsm', '---portland.marketing', 'independent', '1vsm', 'development'),
('portland_pet', 'Portland Pet', 'portland.pet', '1vsm', '---portland.pet', 'independent', '1vsm', 'development'),
('rap_group', 'Rap Group', 'rap.group', '1vsm', '---rap.group', 'independent', '1vsm', 'development'),
('sleep_hiphop', 'Sleep Hip Hop', 'sleep.hiphop', '1vsm', '---sleep.hiphop', 'independent', '1vsm', 'development'),
('syracuse_events', 'Syracuse Events', 'syracuse.events', '1vsm', '---syracuse.events', 'independent', '1vsm', 'development'),
('tyronenorris_com', 'Tyrone Norris', 'tyronenorris.com', '1vsm', '---tyronenorris.com', 'independent', '1vsm', 'development'),
('yh5d_com', 'YH5D', 'yh5d.com', '1vsm', '---yh5d.com', 'independent', '1vsm', 'development');
