-- Migration 057b: Seed default services for Oregon Tires
-- Populates the services table with the existing service pages

INSERT INTO oretir_services (slug, name_en, name_es, description_en, description_es, body_en, body_es, icon, color_hex, color_bg, color_text, color_dark_bg, color_dark_text, color_dot, price_display_en, price_display_es, category, is_bookable, has_detail_page, sort_order, duration_estimate) VALUES
('tire-installation', 'Tire Installation', 'Instalación de Llantas', 'Professional tire mounting, balancing, and installation services.', 'Servicios profesionales de montaje, balanceo e instalación de llantas.', '', '', '🛞', '#3B82F6', 'bg-blue-100', 'text-blue-800', 'dark:bg-blue-900/30', 'dark:text-blue-300', 'bg-blue-500', 'From $20/tire', 'Desde $20/llanta', 'tires', 1, 1, 1, '45-90'),
('tire-repair', 'Tire Repair', 'Reparación de Llantas', 'Flat tire repair, patching, and plugging services.', 'Servicios de reparación, parche y tapón de llantas ponchadas.', '', '', '🔧', '#60A5FA', 'bg-blue-100', 'text-blue-700', 'dark:bg-blue-900/30', 'dark:text-blue-300', 'bg-blue-400', 'From $25', 'Desde $25', 'tires', 1, 1, 2, '30-45'),
('wheel-alignment', 'Wheel Alignment', 'Alineación de Ruedas', 'Precision 4-wheel alignment to extend tire life and improve handling.', 'Alineación de precisión de 4 ruedas para extender la vida de las llantas.', '', '', '🎯', '#8B5CF6', 'bg-purple-100', 'text-purple-800', 'dark:bg-purple-900/30', 'dark:text-purple-300', 'bg-purple-500', 'From $79', 'Desde $79', 'tires', 1, 1, 3, '45-60'),
('brake-service', 'Brake Service', 'Servicio de Frenos', 'Brake inspection, pad replacement, rotor resurfacing, and fluid service.', 'Inspección de frenos, reemplazo de pastillas, rectificado de rotores y servicio de fluidos.', '', '', '🛑', '#EF4444', 'bg-red-100', 'text-red-800', 'dark:bg-red-900/30', 'dark:text-red-300', 'bg-red-500', 'From $149', 'Desde $149', 'maintenance', 1, 1, 4, '60-120'),
('oil-change', 'Oil Change', 'Cambio de Aceite', 'Conventional and synthetic oil change with filter replacement.', 'Cambio de aceite convencional y sintético con reemplazo de filtro.', '', '', '🛢️', '#F97316', 'bg-orange-100', 'text-orange-800', 'dark:bg-orange-900/30', 'dark:text-orange-300', 'bg-orange-500', 'From $39', 'Desde $39', 'maintenance', 1, 1, 5, '30-45'),
('engine-diagnostics', 'Engine Diagnostics', 'Diagnóstico de Motor', 'Computer diagnostics, check engine light, and electrical system testing.', 'Diagnóstico por computadora, luz de check engine y pruebas del sistema eléctrico.', '', '', '🔍', '#06B6D4', 'bg-cyan-100', 'text-cyan-800', 'dark:bg-cyan-900/30', 'dark:text-cyan-300', 'bg-cyan-500', 'From $89', 'Desde $89', 'specialized', 1, 1, 6, '30-60'),
('suspension-repair', 'Suspension Repair', 'Reparación de Suspensión', 'Shocks, struts, springs, and suspension component repair.', 'Amortiguadores, struts, resortes y reparación de componentes de suspensión.', '', '', '🔩', '#10B981', 'bg-emerald-100', 'text-emerald-800', 'dark:bg-emerald-900/30', 'dark:text-emerald-300', 'bg-emerald-500', 'Call for quote', 'Llame para cotización', 'specialized', 1, 1, 7, '60-180'),
('mobile-service', 'Mobile Service', 'Servicio Móvil', 'We come to you — tire changes, jump starts, and roadside repairs.', 'Vamos a donde usted esté — cambios de llantas, arranques y reparaciones.', '', '', '🚐', '#EAB308', 'bg-yellow-100', 'text-yellow-800', 'dark:bg-yellow-900/30', 'dark:text-yellow-300', 'bg-yellow-500', 'From $59', 'Desde $59', 'specialized', 1, 1, 8, '30-60'),
('fleet-services', 'Fleet Services', 'Servicios de Flota', 'Volume pricing and priority service for commercial fleets.', 'Precios por volumen y servicio prioritario para flotas comerciales.', '', '', '🚛', '#6366F1', 'bg-indigo-100', 'text-indigo-800', 'dark:bg-indigo-900/30', 'dark:text-indigo-300', 'bg-indigo-500', 'Custom pricing', 'Precios personalizados', 'specialized', 1, 1, 9, ''),
('roadside-assistance', 'Roadside Assistance', 'Asistencia en Carretera', '24/7 emergency roadside assistance — towing, tire changes, jump starts.', 'Asistencia de emergencia en carretera 24/7 — grúa, cambio de llantas, arranques.', '', '', '🚨', '#F43F5E', 'bg-rose-100', 'text-rose-800', 'dark:bg-rose-900/30', 'dark:text-rose-300', 'bg-rose-500', 'From $75', 'Desde $75', 'specialized', 1, 1, 10, '')
ON DUPLICATE KEY UPDATE name_en = VALUES(name_en), name_es = VALUES(name_es);
