-- Seed blog posts with bilingual content
-- Run AFTER migrate-016-blog.sql

INSERT INTO oretir_blog_posts (slug, title_en, title_es, excerpt_en, excerpt_es, body_en, body_es, status, published_at) VALUES

('5-signs-your-tires-need-replacing',
'5 Signs Your Tires Need Replacing',
'5 Senales de que sus Llantas Necesitan Reemplazo',
'Learn the warning signs that indicate it''s time for new tires. Don''t risk your safety — know when to replace.',
'Aprenda las senales de advertencia que indican que es hora de llantas nuevas. No arriesgue su seguridad.',
'<h2>How to Know When Your Tires Need Replacing</h2><p>Your tires are the only part of your car that touches the road. Worn tires reduce traction, increase stopping distance, and raise the risk of blowouts. Here are five signs it''s time for new tires:</p><h3>1. Low Tread Depth</h3><p>The penny test is simple: insert a penny into the tread with Lincoln''s head facing down. If you can see the top of his head, your tread is below 2/32" and it''s time to replace. For Portland''s rainy conditions, we recommend replacing at 4/32".</p><h3>2. Uneven Wear Patterns</h3><p>If one side of the tire is more worn than the other, you may have alignment or suspension issues. Get the underlying problem fixed and replace the tires.</p><h3>3. Visible Cracks or Bulges</h3><p>Cracks in the sidewall or bulges on the tire surface indicate structural damage. These tires could fail at any time and should be replaced immediately.</p><h3>4. Vibration While Driving</h3><p>Excessive vibration can indicate internal tire damage, uneven wear, or balance issues. Have it inspected right away.</p><h3>5. Age (6+ Years)</h3><p>Even tires with good tread should be replaced after 6-10 years. Rubber degrades over time regardless of use. Check the DOT code on the sidewall for the manufacture date.</p><p><strong>Need new tires?</strong> Oregon Tires carries a wide selection of new and quality used tires, with professional installation starting at $20 per tire.</p>',
'<h2>Como Saber Cuando sus Llantas Necesitan Reemplazo</h2><p>Sus llantas son la unica parte de su auto que toca el camino. Las llantas desgastadas reducen la traccion, aumentan la distancia de frenado y elevan el riesgo de reventones. Aqui hay cinco senales de que es hora de llantas nuevas:</p><h3>1. Profundidad Baja del Dibujo</h3><p>La prueba de la moneda es simple: inserte una moneda en el dibujo. Si puede ver la parte superior, el dibujo esta por debajo de 2/32" y es hora de reemplazar. Para las condiciones lluviosas de Portland, recomendamos reemplazar a 4/32".</p><h3>2. Patrones de Desgaste Desiguales</h3><p>Si un lado de la llanta esta mas desgastado que el otro, puede tener problemas de alineacion o suspension.</p><h3>3. Grietas o Protuberancias Visibles</h3><p>Las grietas en la pared lateral o protuberancias en la superficie indican dano estructural. Estas llantas deben reemplazarse de inmediato.</p><h3>4. Vibracion al Conducir</h3><p>La vibracion excesiva puede indicar dano interno, desgaste desigual o problemas de balanceo.</p><h3>5. Antiguedad (6+ Anos)</h3><p>Incluso las llantas con buen dibujo deben reemplazarse despues de 6-10 anos. El caucho se degrada con el tiempo.</p><p><strong>Necesita llantas nuevas?</strong> Oregon Tires tiene una amplia seleccion con instalacion desde $20 por llanta.</p>',
'published', '2026-02-15 10:00:00'),

('why-wheel-alignment-matters',
'Why Wheel Alignment Matters',
'Por Que la Alineacion de Ruedas es Importante',
'Misaligned wheels cost you money in tire wear and fuel. Learn why regular alignment saves you hundreds.',
'Las ruedas desalineadas le cuestan dinero en desgaste de llantas y combustible. Aprenda por que la alineacion regular le ahorra cientos.',
'<h2>The Hidden Cost of Misaligned Wheels</h2><p>Wheel alignment might seem like an optional service, but ignoring it can cost you hundreds of dollars in premature tire wear, reduced fuel efficiency, and even safety risks.</p><h3>What is Wheel Alignment?</h3><p>Alignment adjusts three angles — camber, caster, and toe — so your wheels point straight and true. When these angles drift, your tires wear unevenly and your car pulls to one side.</p><h3>Signs You Need an Alignment</h3><ul><li>Your car pulls to the left or right</li><li>The steering wheel is off-center when driving straight</li><li>Uneven tire wear (one edge more worn)</li><li>The steering wheel vibrates</li></ul><h3>How Often Should You Get an Alignment?</h3><p>We recommend an alignment check every 12 months or 12,000 miles — whichever comes first. Also get one after hitting a pothole, curb, or after installing new tires.</p><h3>Portland Roads and Alignment</h3><p>Portland''s frequent rain and occasional potholes make alignment checks especially important. Our computerized alignment equipment ensures precision adjustments for your specific vehicle.</p><p><strong>Book your alignment today</strong> — starting at just $75 at Oregon Tires Auto Care.</p>',
'<h2>El Costo Oculto de las Ruedas Desalineadas</h2><p>La alineacion puede parecer un servicio opcional, pero ignorarla puede costarle cientos de dolares en desgaste prematuro de llantas y menor eficiencia de combustible.</p><h3>Que es la Alineacion?</h3><p>La alineacion ajusta tres angulos — camber, caster y convergencia — para que sus ruedas apunten correctamente.</p><h3>Senales de que Necesita Alineacion</h3><ul><li>Su auto se desvia a la izquierda o derecha</li><li>El volante esta descentrado</li><li>Desgaste desigual de llantas</li><li>El volante vibra</li></ul><h3>Con Que Frecuencia?</h3><p>Recomendamos una revision cada 12 meses o 12,000 millas. Tambien despues de golpear un bache o instalar llantas nuevas.</p><p><strong>Reserve su alineacion hoy</strong> — desde solo $75 en Oregon Tires Auto Care.</p>',
'published', '2026-02-10 10:00:00'),

('best-tires-portland-wet-weather',
'Best Tires for Portland''s Wet Weather',
'Las Mejores Llantas para el Clima Lluvioso de Portland',
'Portland gets 43 inches of rain per year. Here''s how to choose tires that keep you safe on wet roads.',
'Portland recibe 43 pulgadas de lluvia al ano. Asi es como elegir llantas que lo mantengan seguro en caminos mojados.',
'<h2>Choosing the Right Tires for Portland Rain</h2><p>With an average of 154 rainy days per year, Portland drivers need tires that perform well in wet conditions. Here''s what to look for:</p><h3>All-Season vs Rain Tires</h3><p>All-season tires work well for most Portland drivers. They handle wet roads, light snow, and dry pavement. For maximum wet grip, dedicated rain tires or touring tires with high wet traction ratings are the best choice.</p><h3>Key Features for Wet Weather</h3><ul><li><strong>Deep tread grooves</strong> — channels water away from the contact patch</li><li><strong>Siping</strong> — tiny slits in the tread blocks grip wet surfaces</li><li><strong>Silica compound</strong> — modern tire compounds grip better when cold and wet</li><li><strong>High UTQG traction rating</strong> — look for AA or A ratings</li></ul><h3>Tire Brands We Recommend</h3><p>At Oregon Tires, we carry quality brands suited for Pacific Northwest weather. Our team can recommend the best option for your vehicle type, driving style, and budget.</p><h3>Don''t Forget Tread Depth</h3><p>New tires have 10/32" of tread. For Portland''s rainy conditions, we strongly recommend replacing tires at 4/32" rather than the legal minimum of 2/32". That extra tread makes a significant difference in wet braking distance.</p><p><strong>Visit us</strong> for a free tire consultation and find the perfect tires for Portland weather.</p>',
'<h2>Eligiendo las Llantas Correctas para la Lluvia de Portland</h2><p>Con un promedio de 154 dias lluviosos al ano, los conductores de Portland necesitan llantas que funcionen bien en condiciones humedas.</p><h3>Toda Temporada vs Llantas para Lluvia</h3><p>Las llantas para toda temporada funcionan bien para la mayoria. Para maximo agarre en mojado, las llantas de turismo con alta calificacion de traccion son la mejor opcion.</p><h3>Caracteristicas Clave</h3><ul><li><strong>Ranuras profundas</strong> — canalizan el agua</li><li><strong>Siping</strong> — pequenas hendiduras que agarran superficies mojadas</li><li><strong>Compuesto de silice</strong> — mejor agarre en frio y mojado</li><li><strong>Alta calificacion UTQG</strong> — busque AA o A</li></ul><h3>No Olvide la Profundidad del Dibujo</h3><p>Para las condiciones de Portland, recomendamos reemplazar llantas a 4/32" en lugar del minimo legal de 2/32".</p><p><strong>Visitenos</strong> para una consulta gratuita de llantas.</p>',
'published', '2026-02-05 10:00:00'),

('how-often-change-oil',
'How Often Should You Change Your Oil?',
'Con Que Frecuencia Debe Cambiar su Aceite?',
'The old 3,000-mile rule is outdated. Learn the modern oil change intervals for your vehicle.',
'La regla de las 3,000 millas esta desactualizada. Conozca los intervalos modernos de cambio de aceite.',
'<h2>Modern Oil Change Intervals</h2><p>The old advice of changing your oil every 3,000 miles is outdated for most vehicles. Modern engines and synthetic oils have extended safe intervals significantly.</p><h3>General Guidelines</h3><ul><li><strong>Conventional oil</strong>: Every 3,000-5,000 miles</li><li><strong>Synthetic blend</strong>: Every 5,000-7,500 miles</li><li><strong>Full synthetic</strong>: Every 7,500-10,000 miles</li></ul><p>Always check your owner''s manual for the manufacturer''s recommendation.</p><h3>Factors That Shorten Intervals</h3><ul><li>Frequent short trips (under 10 miles)</li><li>Stop-and-go city driving</li><li>Towing or hauling heavy loads</li><li>Extreme temperatures</li><li>Dusty conditions</li></ul><h3>What Happens If You Wait Too Long?</h3><p>Old oil breaks down, loses viscosity, and fails to protect engine components. This leads to increased friction, overheating, sludge buildup, and eventually expensive engine damage.</p><h3>What''s Included in Our Oil Change?</h3><p>Every oil change at Oregon Tires includes a new oil filter, fluid level check and top-off, tire pressure check, and a visual multi-point inspection — all starting at just $35.</p>',
'<h2>Intervalos Modernos de Cambio de Aceite</h2><p>El viejo consejo de cambiar aceite cada 3,000 millas esta desactualizado para la mayoria de los vehiculos.</p><h3>Guia General</h3><ul><li><strong>Aceite convencional</strong>: Cada 3,000-5,000 millas</li><li><strong>Mezcla sintetica</strong>: Cada 5,000-7,500 millas</li><li><strong>Sintetico completo</strong>: Cada 7,500-10,000 millas</li></ul><h3>Factores que Acortan Intervalos</h3><ul><li>Viajes cortos frecuentes</li><li>Conduccion en ciudad</li><li>Remolque o cargas pesadas</li><li>Temperaturas extremas</li></ul><h3>Que Incluye Nuestro Cambio de Aceite?</h3><p>Cada cambio incluye filtro nuevo, revision de fluidos, presion de llantas e inspeccion visual — desde solo $35.</p>',
'published', '2026-01-28 10:00:00'),

('brake-warning-signs',
'Brake Warning Signs Every Driver Should Know',
'Senales de Advertencia de Frenos que Todo Conductor Debe Conocer',
'Don''t ignore these brake warning signs. Early detection prevents costly repairs and keeps you safe.',
'No ignore estas senales de advertencia de frenos. La deteccion temprana previene reparaciones costosas.',
'<h2>Know Your Brake Warning Signs</h2><p>Your brakes are your vehicle''s most important safety system. Catching problems early can save you money and prevent dangerous situations on the road.</p><h3>1. Squealing or Squeaking</h3><p>Most brake pads have built-in wear indicators — small metal tabs that contact the rotor when pads are low. That high-pitched squeal is your brakes telling you it''s time for new pads.</p><h3>2. Grinding Sound</h3><p>If squealing progresses to grinding, the pads are completely worn and metal is contacting metal. This damages your rotors and dramatically increases repair costs. Don''t wait.</p><h3>3. Pulsating Brake Pedal</h3><p>A pulsating or vibrating brake pedal usually indicates warped rotors. This happens from excessive heat buildup, often from aggressive braking or prolonged braking downhill.</p><h3>4. Soft or Spongy Pedal</h3><p>If the brake pedal feels soft or sinks to the floor, you may have air in the brake lines or a brake fluid leak. This is a serious safety concern — have it inspected immediately.</p><h3>5. Warning Light</h3><p>The brake warning light on your dashboard could indicate low brake fluid, worn pads (on vehicles with sensors), or an ABS system issue. Never ignore it.</p><h3>6. Pulling to One Side</h3><p>If your car pulls when braking, you may have a stuck caliper, uneven pad wear, or a brake hose issue.</p><p><strong>Brake inspection at Oregon Tires</strong> starts at just $100 and includes a full assessment of pads, rotors, calipers, lines, and fluid condition.</p>',
'<h2>Conozca las Senales de Advertencia de sus Frenos</h2><p>Sus frenos son el sistema de seguridad mas importante de su vehiculo.</p><h3>1. Chirrido</h3><p>La mayoria de las pastillas tienen indicadores de desgaste que producen un sonido agudo cuando estan bajas.</p><h3>2. Sonido de Molienda</h3><p>Si el chirrido progresa a molienda, las pastillas estan completamente desgastadas y metal contacta metal.</p><h3>3. Pedal Pulsante</h3><p>Un pedal pulsante generalmente indica rotores alabeados por acumulacion excesiva de calor.</p><h3>4. Pedal Suave o Esponjoso</h3><p>Si el pedal se siente suave, puede tener aire en las lineas o una fuga de liquido de frenos.</p><h3>5. Luz de Advertencia</h3><p>La luz de frenos puede indicar liquido bajo, pastillas desgastadas o un problema del sistema ABS.</p><h3>6. Jalon hacia un Lado</h3><p>Si su auto se desvia al frenar, puede tener un caliper atascado o desgaste desigual.</p><p><strong>La inspeccion de frenos en Oregon Tires</strong> comienza desde $100 e incluye evaluacion completa.</p>',
'published', '2026-01-20 10:00:00')

ON DUPLICATE KEY UPDATE title_en = VALUES(title_en);

-- Link posts to categories
INSERT INTO oretir_blog_post_categories (post_id, category_id)
SELECT p.id, c.id FROM oretir_blog_posts p, oretir_blog_categories c
WHERE (p.slug = '5-signs-your-tires-need-replacing' AND c.slug = 'tires')
   OR (p.slug = '5-signs-your-tires-need-replacing' AND c.slug = 'safety')
   OR (p.slug = 'why-wheel-alignment-matters' AND c.slug = 'maintenance')
   OR (p.slug = 'best-tires-portland-wet-weather' AND c.slug = 'tires')
   OR (p.slug = 'best-tires-portland-wet-weather' AND c.slug = 'seasonal')
   OR (p.slug = 'how-often-change-oil' AND c.slug = 'maintenance')
   OR (p.slug = 'brake-warning-signs' AND c.slug = 'safety')
ON DUPLICATE KEY UPDATE post_id = VALUES(post_id);
