-- Seed Testimonials: 12 existing hardcoded reviews with EN and ES text
INSERT INTO oretir_testimonials (customer_name, rating, review_text_en, review_text_es, sort_order) VALUES
('Maria Rodriguez', 5,
 'Excellent service! They installed my new tires quickly and the price was very fair. The staff speaks Spanish which made communication easy.',
 '¡Excelente servicio! Instalaron mis llantas nuevas rápidamente y el precio fue muy justo. El personal habla español, lo que facilitó la comunicación.',
 1),
('James Thompson', 5,
 'Been coming here for years. They always do quality work and are honest about what needs to be done.',
 'Vengo aquí desde hace años. Siempre hacen trabajo de calidad y son honestos sobre lo que se necesita hacer.',
 2),
('Sarah Chen', 5,
 'Fast and professional service. Had a flat tire emergency and they got me back on the road in 30 minutes.',
 'Servicio rápido y profesional. Tuve una emergencia con una llanta ponchada y me pusieron de vuelta en el camino en 30 minutos.',
 3),
('Roberto Gonzalez', 5,
 'Excellent service! They helped me with my tire alignment. Very friendly staff and fair prices.',
 '¡Servicio excelente! Me ayudaron con la alineación de mis llantas. Personal muy amable y precios justos.',
 4),
('Jennifer Smith', 4,
 'Good experience overall. They diagnosed my car trouble quickly and fixed it at a reasonable price.',
 'Buena experiencia en general. Diagnosticaron el problema de mi carro rápidamente y lo repararon a un precio razonable.',
 5),
('Miguel Santos', 5,
 'Very helpful staff. They explained everything clearly in Spanish and English. Quality tire installation.',
 'Personal muy servicial. Explicaron todo claramente en español e inglés. Instalación de llantas de calidad.',
 6),
('David Miller', 5,
 'Oregon Tires always takes care of my family''s vehicles. Honest, reliable service.',
 'Oregon Tires siempre cuida los vehículos de mi familia. Servicio honesto y confiable.',
 7),
('Carmen Lopez', 5,
 'I love this place! They always treat me well and do excellent work.',
 '¡Me encanta este lugar! Siempre me tratan bien y hacen un trabajo excelente.',
 8),
('Lisa Johnson', 5,
 'Amazing customer service! They went above and beyond to help with my tire emergency.',
 '¡Increíble servicio al cliente! Hicieron todo lo posible para ayudarme con mi emergencia de llanta.',
 9),
('Carlos Ramirez', 5,
 'Excellent customer service. They repaired my tire quickly and with warranty.',
 'Excelente atención al cliente. Repararon mi llanta rápidamente y con garantía.',
 10),
('Christine Clark', 5,
 'Love this place! They''re honest, reliable, and do great work.',
 '¡Me encanta este lugar! Son honestos, confiables y hacen un gran trabajo.',
 11),
('Mark Wilson', 5,
 'Been a customer for over 10 years. Always reliable, fair prices, and quality work.',
 'He sido cliente por más de 10 años. Siempre confiables, precios justos y trabajo de calidad.',
 12);
